name: Continuous Delivery with GitHub Container Registry

on:
  push:
    paths:
      - 'pom.xml'
      - 'src/**'
      - Dockerfile
  
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Run tests
      run: mvn test
    - name: Build image
      run: mvn spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=items
    - name: Login to GitHub Docker Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Push image to GitHub Container Registry
      run: |
        IMAGE_VERSION=$(date +'%Y%m%d.%H%M%S')-ghcr
        IMAGE_USER=$(echo ${{ github.repository_owner }} | awk '{print tolower($0)}')
        docker tag items ghcr.io/$IMAGE_USER/items:$IMAGE_VERSION
        docker push ghcr.io/$IMAGE_USER/items:$IMAGE_VERSION
        
