name: Continuous Delivery with DockerHub (Docker Actions)

on:
  push:
    paths:
      - 'pom.xml'
      - 'src/**'
      - 'Dockerfile'
  
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Run tests
      run: mvn test
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/items:docker-action
        
